--- #YAML:1.0
name:                Date-Extract-P800Picture
version:             0.01
abstract:            class for extracting date and
license:             ~
author:              
    - Roland van Ipenburg <ipenburg@xs4all.nl>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Meta::Express:          0.1
    DateTime:                      0.45
    English:                       1.04
    Error:                         0.17
    POSIX:                         1.13
    Readonly:                      1.03
    Test::More:                    0.86
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
