---
abstract: 'class for extracting the date and the hour from'
author:
  - 'Roland van Ipenburg <ipenburg@xs4all.nl>'
build_requires:
  Test::More: 0.81
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Extract-P800Picture
provides:
  Date::Extract::P800Picture:
    file: lib/Date/Extract/P800Picture.pm
    version: 0.103
requires:
  DateTime: 0
  English: 0
  Exception::Class: 0
  Moose: 0
  POSIX: 0
  Readonly: 0
  namespace::autoclean: 0
  perl: v5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.103
