--- #YAML:1.0
name:               Date-Extract-P800Picture
version:            0.04
abstract:           class for extracting the date and the hour from
author:
    - Roland van Ipenburg <ipenburg@xs4all.nl>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Meta::Express:  0
    DateTime:             0
    English:              0
    Error:                0
    POSIX:                0
    Readonly:             0
    Test::More:           0.81
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
